# ==================================================
# Cloudflare Pages Configuration
# ==================================================

name = "ftth-tool"
compatibility_date = "2024-01-01"


# Environment variables (production)
[env.production]
name = "ftth-tool"

# Environment variables (preview)
[env.preview]
name = "ftth-tool-preview"
